### ISSUE TITLE
[FE] Animate the Logo SVG

### ISSUE THREAD

**Issue by edichoska** [learnhubmkd/app#117]

**Comment by RevanchistX** [comment]
I can't remember what this was for - @edichoska 
Do you you have any specific animation in mind?
We can have the LH Logo be used as an arrow perhaps?
Anyways, please provide more info or a reference

**Comment by RevanchistX** [comment]
https://github.com/learnhubmkd/app/assets/11035261/67598935-c84d-4afe-958c-1570b22d044f


https://github.com/learnhubmkd/app/assets/11035261/8d96acec-0efc-4be1-b90c-c35dad873f0d

**Comment by RevanchistX** [comment]
https://github.com/learnhubmkd/app/assets/11035261/ed481cce-7fff-4254-872e-7f05c60977d8
