### ISSUE TITLE
[FE] Social Icons Component

### ISSUE THREAD

**Issue by RevanchistX** [learnhubmkd/app#180]
Component is under review, do not touch.

Social Icons component should be a reusable component that can take in a list of icons to and render them with spacing in between them. 

Examples:

![Image](https://github.com/learnhubmkd/app/assets/11035261/7ec5bb56-ea49-49e8-a810-707f6475e2f2)

![Image](https://github.com/learnhubmkd/app/assets/11035261/8b8add86-720f-4077-b399-48a90181e35e)

Discord: https://discord.com/invite/nUEKUWVveW
LinkedIn: https://www.linkedin.com/company/learnhubmk/
GitHub: https://github.com/learnhubmkd
Facebook: https://www.facebook.com/profile.php?id=61556614894387
Youtube: https://www.youtube.com/channel/UCDDywMbRvBXuUFTPBORc-BQ
Instagram: https://www.instagram.com/learnhub.mk
X: https://x.com/learnhubmk

**Comment by edichoska** [comment]
The Design was changed and the section we previously had in contact and footer is no longer there.
We are closing this issue. @ninman27
