### ISSUE TITLE
[FE] Reusable UI Components and Folder Structure Setup

### ISSUE THREAD

**Issue by aleksandralazoroska** [learnhubmkd/app#20]
Description

The goal of this task is to create a modular and reusable set of UI components for a web application. Each component should be organized within its folder, and a corresponding `style.scss` file should be included to manage the component's styling. 

- Folder Structure
- Components
- Button Component

Considerations
- Should support various sizes (small, medium, large).
- Customizable colours to align with the application's theme.
- Include hover and active states.

Acceptance Criteria:

- Renders without errors.
- Clicking triggers the expected action.
- Supports different sizes and colours.

Navbar Component

Description
The Navbar component provides a navigation bar for the application.

Considerations
- Responsive design for various screen sizes.
- Supports dynamic menu items.
- Customizable logo and background.

Acceptance Criteria:
- Renders without errors.
- Navigate to the correct pages on item selection.
- Adapts to different screen sizes appropriately.

Styling

1. Global Styles

- **`main.scss`:**
  - Imports all component styles.
  - Includes global styles like resets.
  - Combines and compiles styles for the entire application.

2. Component-specific Styles

- **`style.scss` within each component folder:**
  - Contains styles specific to the respective component.
  - Follows BEM (Block, Element, Modifier) naming convention.
  - Imports variables and mixins from the global styles.

**Comment by davorminchorov** [comment]
We will have at least 3 main modules (applications) at the start:

Website - everything related to the website will be here (blog, contact, newsletter etc.)
Platform - The members area
Admin - The admin area

So consider creating a modular monolith architecture similar so that it will be easier to work with and split later on if needed.

**Comment by edichoska** [comment]
Yes, that is a great note.
But we also need a folder with generic components that will be reused everywhere, that are not module specific.
