### ISSUE TITLE
[FE] Fix layout responsiveness + logo size on mobile

### ISSUE THREAD

**Issue by stoimenov95** [learnhubmkd/app#206]
![Image](https://github.com/learnhubmkd/app/assets/32269810/7bdc79f9-3ea0-4499-9066-fca4f4e60c2d)

The whole page layout should be centered, and the margin on the right should be removed. Additionally, the size of the logo should be set proportionally.

This is currently happening on lower (mobile) resolutions, but It would be great if other resolutions were checked as well.

**Comment by edichoska** [comment]
@stoimenov95 can you please elaborate?
Is this regarding the new design?

**Comment by stoimenov95** [comment]
@edichoska Will provide more info, I should've kept it in the Backlog...

**Comment by edichoska** [comment]
This is connected to the #221
