### ISSUE TITLE
[FE] Optimize image performance

### ISSUE THREAD

**Issue by RevanchistX** [learnhubmkd/app#229]
When running `build-dev`, several warnings and suggestions related to images show up.
1. Update the component to resolve this change.
 ![image](https://github.com/learnhubmkd/app/assets/11035261/e3a6fd1f-66c6-42c1-b592-6a4b1eab5ae6)

2. There are some NextJS recommendations with `npm i sharp`, please resolve this as well.
Update: issue appeared due to different yarn versions, sharp is already installed.

**Comment by RevanchistX** [comment]
Hey, @ninman27 

@edichoska mentioned you implemented `sharp` for the project. 
I keep seeing this recommendation: (as mentioned in point 2. of the ticket)
![image](https://github.com/learnhubmkd/app/assets/11035261/55b28ae3-cee1-40d0-bd93-6f742e743b88)

However, after a little bit of investigating, I noticed this only shows up when using `yarn build` and **not** when using `npm run build`.  It seems there's a minor version upgrade `0.33.2 -> 0.33.3` for `sharp`. 

Can you look into this and let me know what you find?
If just the version upgrade solves the problem, that's fine by me.

**Comment by kire21** [comment]
@RevanchistX I tried with yarn build and it is OK. I don't see Next.js's recommendation about the sharp.

![image](https://github.com/learnhubmkd/app/assets/58231146/5da0d219-f126-4e49-b394-33b86a8899d9)

**Comment by RevanchistX** [comment]
Thanks for the feedback @kire21 
It seems we have different yarn versions, but I don't think this is an issue anymore.
I will update the ticket.
