### ISSUE TITLE
[FE] Setup Jest and React Testing Library for Automated Testing

### ISSUE THREAD

**Issue by stoimenov95** [learnhubmkd/app#55]
**Objective:**

Integrate Jest and React Testing Library to establish a framework for automated testing within the application. This will ensure that components and functionality are tested from the start, leading to a more reliable codebase.

**Tasks:**

- Install Jest and React Testing Library, along with necessary configurations.

- Write sample unit tests for an existing component.

- Document guidelines for writing and running tests.

**Acceptance Criteria:**

- Jest and React Testing Library are correctly set up.

- Sample tests are written and successfully pass.

- Documentation provides clear instructions on testing practices.

**Comment by stoimenov95** [comment]
@edichoska @DimitarHristovski should we write the tests in TS as well?

**Comment by edichoska** [comment]
> [@edichoska](https://github.com/edichoska) [@DimitarHristovski](https://github.com/DimitarHristovski) should we write the tests in TS as well?

yes
