### ISSUE TITLE
[FE]Create a Nested Layout that will contain the side bar. This will be used in blogs page.

### ISSUE THREAD

**Issue by edichoska** [learnhubmkd/app#65]
**Objective:**
Create a nested layout component to accommodate the sidebar we will have in the blogs page, and individual blogs page

**Task:**
- Implement a new nested layout component that will be inside the blogs directory.

**Implementation Notes:**
- Take a look at the documentation and make sure you are using Typescript: https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts

_Useful Link:_ https://blog.logrocket.com/guide-next-js-layouts-nested-layouts/

**Comment by ninman27** [comment]
![Image](https://github.com/learnhubmkd/app/assets/161211853/671668c3-2e80-40b8-afdd-99ff689bed88)

**Comment by edichoska** [comment]
@ninman27  You should add the screenshot to the PR not the tiket
