### ISSUE TITLE
[FE] Create a custom cursor

### ISSUE THREAD

**Issue by edichoska** [learnhubmkd/app#67]
**Objective:**
Introduce a custom cursor design to enhance the visual and interactive experience of the application.

**Task:**
- Create a custom cursor design and implement it across the application. 
- The cursor should look like the dot from the logo. When we are in the Blogs Section it should transform and be bigger. Check out Figma file for the details on how it will look.

Inspiration:
https://www.scalzodesign.be/

**Comment by KonstantinVchkov** [comment]
i have made a pull request heres's the link of the pr https://github.com/learnhubmkd/app/pull/84

**Comment by stoimenov95** [comment]
@edichoska can you please share the Figma file link? I wasn't able to find the design for the cursor in the existing file, and I am having some doubts regarding the 'Next' text in the cursor when hovering over the blog section.

**Comment by edichoska** [comment]
@stoimenov95  I don't have a Figma example of how this would look.
<img width="573" alt="Screenshot 2024-03-29 at 12 38 27" src="https://github.com/learnhubmkd/app/assets/105276163/62cfa508-2fec-4ba8-a54e-15fc371c8db0">

I was imagining something like this:
If it is looking "weird" maybe we can only have the arrow.

**Comment by stoimenov95** [comment]
@edichoska only the arrow looks much better instead of the 'Next' text IMO.

**Comment by Mikivitkovski** [comment]
![image](https://github.com/learnhubmkd/app/assets/46110686/4b055afe-b105-42b6-a066-941d3f472d41)
I cand change like this to be if you want ? 
and also i change the name of the section .large to .largeCursor
