### ISSUE TITLE
[FE] Create the Hero Section

### ISSUE THREAD

**Issue by edichoska** [learnhubmkd/app#70]
**Task:**
- Implement the Hero Section as shown in the Figma file: https://www.figma.com/file/zhRSxKmdeXlsdStdL6NdgU/Untitled?type=design&node-id=0-1&mode=design&t=VgX6o5TWVv38P8ns-0
(at this phase do not worry about responsiveness)

**Comment by ninman27** [comment]
![Image](https://github.com/learnhubmkd/app/assets/161211853/c03c08d9-135a-4918-b313-037fed3364e7)

**Comment by edichoska** [comment]
Thank you! Looks great ⭐
