### ISSUE TITLE
[FE] Create the Blogs Section

### ISSUE THREAD

**Issue by edichoska** [learnhubmkd/app#75]
**Task:**
- Implement the Blogs Section as shown in the Figma file: https://www.figma.com/file/zhRSxKmdeXlsdStdL6NdgU/Untitled?type=design&node-id=0-1&mode=design&t=VgX6o5TWVv38P8ns-0
- When we click on the button we should be redirected to the Blogs Page
- When we click on the card we should be redirected to the Individual Blog Page
(at this phase do not worry about responsiveness)

**Comment by kire21** [comment]
![Image](https://github.com/learnhubmkd/app/assets/58231146/a03a61b8-ba83-43c0-85b4-c48bd2ecdfcf)



![Image](https://github.com/learnhubmkd/app/assets/58231146/94017135-d4bb-4961-a5f5-3f42c47a5f40)
