### ISSUE TITLE
Create Wiki for Development Workflow Documentation

### ISSUE THREAD

**Issue by edichoska** [learnhubmkd/app#90]
**Summary:**
Create a GitHub Wiki to document our team's processes for creating branches, pull requests (PRs), and naming conventions. The aim is to standardize our development workflow, enhance collaboration, and onboard new team members more efficiently.
 
**Include:** 
**Naming Conventions:** Establish naming conventions for branches, PRs, and commit messages to maintain consistency and readability.
**Creating Pull Requests:** Guide on creating PRs, including descriptions, linking issues, and tagging reviewers.
**Review Process:** Outline the process for reviewing PRs, including coding standards, testing requirements, and how to provide constructive feedback.

**Comment by stoimenov95** [comment]
@edichoska please take a look at the wiki, if you think we need to add something please text me. Also, I think we will need some coding standards wiki page.

**Comment by edichoska** [comment]
@davorminchorov @KonstantinVchkov @RevanchistX

**Comment by edichoska** [comment]
@stoimenov95  not sure what else we need. Should we include cloning the repo?
Also assigning tikets, moving them to In Progress and In review . Resolving conflicts.
About the branch naming we were talking about naming them like <tiket-number> - <title-of-the-tiket> ex: 68-create-navigation.

**Comment by davorminchorov** [comment]
We could also add that the commit messages should have a meaning instead of "fix" or "add" or something cryptic like that.

**Comment by stoimenov95** [comment]
@edichoska @davorminchorov @KonstantinVchkov @RevanchistX I would appreciate your thoughts regarding my latest update on the Wiki. Thanks, everyone!
